---

name: Set Secrets

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "What repository?"
        type: choice
        required: true
        options:
          - hello_world
          - milestones_api
          - docker_shared

      env:
        description: "Set environment or repository level secrets?"
        type: choice
        default: "dev"
        options:
          - dev
          - staging
          - prod
          - repo

env:
  VAULT: "set-github-secrets"
  DEBUG: "true"

jobs:
  get-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          # Persist the 1Password Service Account Authorization token
          # for next steps.
          # Keep in mind that every single step in the job is now
          # able to access the token.
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Get Secret Notes from ${{ env.VAULT }} note ${{ inputs.repo }}_${{ inputs.env }}
        run: |
          FILE=$(mktemp)
          # Note that the notes are named by convention
          op read --out-file ${FILE} --force "op://${{ env.VAULT }}/${{ inputs.repo }}_${{ inputs.env }}/notesPlain" > /dev/null
          cat ${FILE}
